const fs = require('fs');
const path = require('path');
const https = require('https');
const os = require('os');
const { execSync } = require('child_process');

const pkg = require('../package.json');
const version = pkg.version;
const repo = 'zhMoody/llmux-cli'; 

const platform = os.platform(); // 'win32', 'darwin', 'linux'
const arch = os.arch();         // 'x64', 'arm64'

// Mapping platform-arch to the suffixes generated by `build.ts`
const targetMap = {
  'win32-x64': { name: 'llmux-windows-x64.exe', ext: '.exe' },
  'linux-x64': { name: 'llmux-linux-x64', ext: '' },
  'linux-arm64': { name: 'llmux-linux-arm64', ext: '' },
  'darwin-x64': { name: 'llmux-macos-x64', ext: '' },
  'darwin-arm64': { name: 'llmux-macos-arm64', ext: '' }
};

const targetKey = `${platform}-${arch}`;
const target = targetMap[targetKey];

if (!target) {
    console.error(`🔴 LLMux does not provide pre-compiled binaries for ${targetKey}.`);
    console.error('You will need to use Bun to run it from source: bun install -g llmux-cli');
    process.exit(0); // Exit safely without breaking the install flow
}

const binDir = path.join(__dirname, '../bin');
if (!fs.existsSync(binDir)) {
    fs.mkdirSync(binDir, { recursive: true });
}

const exePath = path.join(binDir, `llmux${target.ext}`);
// We fetch directly from the Tag matching the exact version
const url = `https://github.com/${repo}/releases/download/v${version}/${target.name}`;

console.log(`\n📦 LLMux NPM Postinstall Hooks`);
console.log(`⏬ Downloading LLMux native binary for ${targetKey}...`);
console.log(`🔗 URL: ${url}`);

function download(url, dest) {
    return new Promise((resolve, reject) => {
        const file = fs.createWriteStream(dest);
        https.get(url, (response) => {
            if (response.statusCode === 301 || response.statusCode === 302) {
                return download(response.headers.location, dest).then(resolve).catch(reject);
            }
            if (response.statusCode !== 200) {
                return reject(new Error(`Failed to download binary, HTTP status code: ${response.statusCode}`));
            }
            response.pipe(file);
            file.on('finish', () => {
                file.close();
                if (platform !== 'win32') {
                    execSync(`chmod +x "${dest}"`);
                }
                resolve();
            });
        }).on('error', (err) => {
            fs.unlinkSync(dest);
            reject(err);
        });
    });
}

// Download the binary, silently suppress hard failure so the pure-Node/Bun users can still clone/fallback to bun
download(url, exePath)
    .then(() => {
        console.log("✅ LLMux native binary successfully installed!\n");
    })
    .catch((err) => {
        console.warn(`⚠️ Failed to download native binary. Error: ${err.message}`);
        console.warn('Fallback: LLMux will attempt to use the local Bun runtime to execute the TypeScript source instead if available.\n');
    });
